component extends="algid.inc.resource.base.model" {
	public struct function get__instance() {
		var result = super.get__instance();
		
		// If there is not a value for the _id then it should be autogenerated
		if(structKeyExists(result, '_id') and result['_id'] eq '') {
			result['_id'] = createUUID();
			this.set_ID(result['_id']);
		}
		
		return result;
	}
}
